# Generated by Django 6.1 on 2026-08-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ufr',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('sigle', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ufr',
                'ordering': ['nom'],
            },
        ),
    ]
