# Generated by Django 6.1 on 2026-08-28 15:31

import core.utils
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.CharField(default=core.utils.generate_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('filiere', models.CharField(max_length=255)),
                ('niveau', models.CharField(max_length=32)),
                ('annee_academique', models.CharField(max_length=16)),
                ('ufr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groupes', to='core.ufr')),
            ],
            options={
                'db_table': 'groupe',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.CharField(default=core.utils.generate_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('ine', models.CharField(max_length=64, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('filiere', models.CharField(max_length=255)),
                ('niveau', models.CharField(max_length=32)),
                ('annee_academique', models.CharField(max_length=16)),
                ('ufr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='core.ufr')),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='referentiel.groupe')),
            ],
            options={
                'db_table': 'etudiant',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.CharField(default=core.utils.generate_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('batiment', models.CharField(max_length=255)),
                ('capacite', models.PositiveIntegerField()),
                ('structure_gestionnaire', models.CharField(choices=[('UFR', 'Ufr'), ('DEP', 'Dep')], default='UFR', max_length=8)),
                ('type_usage', models.CharField(choices=[('propre', 'Propre'), ('commune', 'Commune'), ('louee', 'Louee'), ('gratuite', 'Gratuite')], max_length=16)),
                ('ufr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salles', to='core.ufr')),
            ],
            options={
                'db_table': 'salle',
            },
        ),
        migrations.CreateModel(
            name='UniteEnseignement',
            fields=[
                ('id', models.CharField(default=core.utils.generate_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('intitule', models.CharField(max_length=255)),
                ('niveau', models.CharField(max_length=32)),
                ('ufr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ues', to='core.ufr')),
            ],
            options={
                'db_table': 'unite_enseignement',
            },
        ),
        migrations.AddIndex(
            model_name='groupe',
            index=models.Index(fields=['ufr'], name='groupe_ufr_id_46d9e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupe',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nom'), name='groupe_nom_lower_unique'),
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['groupe'], name='etudiant_groupe__aa8355_idx'),
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['ufr'], name='etudiant_ufr_id_54790e_idx'),
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['ufr', 'annee_academique'], name='etudiant_ufr_id_8c1ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['ufr', 'filiere'], name='etudiant_ufr_id_a27187_idx'),
        ),
        migrations.AddIndex(
            model_name='salle',
            index=models.Index(fields=['ufr'], name='salle_ufr_id_b41f4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='salle',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nom'), name='salle_nom_lower_unique'),
        ),
        migrations.AddConstraint(
            model_name='salle',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('structure_gestionnaire', 'UFR'), ('ufr__isnull', False)), models.Q(('structure_gestionnaire', 'DEP'), ('ufr__isnull', True)), _connector='OR'), name='salle_structure_gestionnaire_coherente'),
        ),
        migrations.AddIndex(
            model_name='uniteenseignement',
            index=models.Index(fields=['ufr'], name='unite_ensei_ufr_id_0987da_idx'),
        ),
        migrations.AddConstraint(
            model_name='uniteenseignement',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('intitule'), name='ue_intitule_lower_unique'),
        ),
    ]
