# Generated by Django 6.1 on 2026-09-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0007_v6_groupe_nom_unique_par_annee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salle',
            name='batiment',
        ),
        migrations.RemoveField(
            model_name='uniteenseignement',
            name='niveau',
        ),
        migrations.AlterField(
            model_name='salle',
            name='type_usage',
            field=models.CharField(choices=[('cours', 'Cours'), ('td', 'TD'), ('tp', 'TP'), ('laboratoire', 'Laboratoire')], max_length=16),
        ),
    ]
