# Generated by Django 6.1 on 2026-09-16 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0008_v7_retours_gestionnaires'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salle',
            name='salle_structure_gestionnaire_coherente',
        ),
        migrations.RemoveIndex(
            model_name='salle',
            name='salle_ufr_id_b41f4a_idx',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='structure_gestionnaire',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='ufr',
        ),
    ]
