# Generated by Django 6.1 on 2026-09-21
#
# [V8] Réforme « Niveau / Spécialité » (2026-09-21).
#
# Strictement ADDITIVE : une nouvelle table `specialite` et une colonne
# `groupe.specialite` avec une valeur par défaut vide. Aucun groupe existant
# n'est modifié, aucune donnée n'est réécrite — les groupes déjà saisis se
# retrouvent simplement « sans spécialité », ce qui est l'état correct pour
# eux (ils ont été créés avant que le choix n'existe) et reste modifiable
# groupe par groupe (PATCH /api/groupes/<id>).
#
# Rien à rétro-remplir depuis l'ancien champ `niveau` : contrairement à ce
# que le vocabulaire de l'écran laissait croire, la colonne nommée `niveau`
# contenait bien des niveaux (L1…M2) — c'est le LIBELLÉ affiché qui disait
# « Parcours » à tort. La réforme corrige donc un mot, pas des données.

import core.utils
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0009_v7_salles_referentiel_partage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='specialite',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.CharField(default=core.utils.generate_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('niveau', models.CharField(max_length=32)),
                ('libelle', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialites', to='referentiel.departement')),
            ],
            options={
                'db_table': 'specialite',
                'ordering': ['libelle'],
                'indexes': [models.Index(fields=['departement', 'niveau'], name='specialite_departe_2f25cc_idx')],
                'constraints': [models.UniqueConstraint(models.F('departement'), models.F('niveau'), django.db.models.functions.text.Lower('libelle'), name='specialite_libelle_dep_niveau_unique')],
            },
        ),
    ]
