# Generated by Django 6.1 on 2026-08-28 15:31

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.CharField(default=core.utils.generate_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'enseignant',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.CharField(default=core.utils.generate_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('identifiant', models.CharField(max_length=255, unique=True)),
                ('mot_de_passe_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('etudiant', 'Etudiant'), ('enseignant', 'Enseignant'), ('scolarite', 'Scolarite'), ('admin', 'Admin')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur', to='accounts.enseignant')),
                ('etudiant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur', to='referentiel.etudiant')),
                ('ufr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gestionnaires', to='core.ufr')),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(default=core.utils.generate_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.utilisateur')),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='EnseignantUfr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ufrs', to='accounts.enseignant')),
                ('ufr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignants', to='core.ufr')),
            ],
            options={
                'db_table': 'enseignant_ufr',
                'constraints': [models.UniqueConstraint(fields=('enseignant', 'ufr'), name='enseignant_ufr_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='utilisateur',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'scolarite'), ('ufr__isnull', False)), models.Q(models.Q(('role', 'scolarite'), _negated=True), ('ufr__isnull', True)), _connector='OR'), name='utilisateur_scolarite_requiert_ufr'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['utilisateur'], name='session_utilisa_5f2096_idx'),
        ),
    ]
