# Generated by Django 6.1 on 2026-08-28 15:31

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.CharField(default=core.utils.generate_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi')], max_length=16)),
                ('heure_debut_minutes', models.PositiveIntegerField()),
                ('heure_fin_minutes', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('normal', 'Normal'), ('modifie', 'Modifie'), ('annule', 'Annule')], default='normal', max_length=16)),
                ('motif', models.TextField(blank=True, null=True)),
                ('derogation_motif', models.TextField(blank=True, null=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creneaux', to='accounts.enseignant')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creneaux', to='referentiel.groupe')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creneaux', to='referentiel.salle')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creneaux', to='referentiel.uniteenseignement')),
            ],
            options={
                'db_table': 'creneau',
            },
        ),
        migrations.CreateModel(
            name='ConflitJournal',
            fields=[
                ('id', models.CharField(default=core.utils.generate_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('salle', 'Salle'), ('enseignant', 'Enseignant'), ('groupe', 'Groupe'), ('capacite', 'Capacite')], max_length=16)),
                ('gravite', models.CharField(choices=[('bloquant', 'Bloquant'), ('avertissement', 'Avertissement')], max_length=16)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('derogation_motif', models.TextField(blank=True, null=True)),
                ('detecte_le', models.DateTimeField(auto_now_add=True)),
                ('detecte_par', models.CharField(max_length=255)),
                ('creneau_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflits_a', to='planning.creneau')),
                ('creneau_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflits_b', to='planning.creneau')),
            ],
            options={
                'db_table': 'conflit_journal',
            },
        ),
        migrations.AddIndex(
            model_name='creneau',
            index=models.Index(fields=['salle', 'jour'], name='creneau_salle_i_f3b16c_idx'),
        ),
        migrations.AddIndex(
            model_name='creneau',
            index=models.Index(fields=['enseignant', 'jour'], name='creneau_enseign_f76110_idx'),
        ),
        migrations.AddIndex(
            model_name='creneau',
            index=models.Index(fields=['groupe', 'jour'], name='creneau_groupe__868f16_idx'),
        ),
        migrations.AddConstraint(
            model_name='creneau',
            constraint=models.CheckConstraint(condition=models.Q(('statut', 'normal'), models.Q(('motif__isnull', False), models.Q(('motif', ''), _negated=True)), _connector='OR'), name='creneau_motif_requis_si_non_normal'),
        ),
        migrations.AddIndex(
            model_name='conflitjournal',
            index=models.Index(fields=['detecte_le'], name='conflit_jou_detecte_ad6ad8_idx'),
        ),
    ]
