# Generated by Django 6.1 on 2026-09-21
#
# [V8.1] Affectation d'un créneau à une spécialité (2026-09-21).
#
# Strictement ADDITIVE : une colonne `creneau.specialite` par défaut vide et
# un index. Aucun créneau existant n'est modifié — ils se retrouvent tous
# « concernant tout le groupe », ce qui est exactement leur sens actuel
# (ils ont été saisis quand un groupe était indivisible). Le programme
# public d'un groupe sans aucune affectation reste donc identique à ce
# qu'il était, séance pour séance.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_v3_retirer_roles_consultation'),
        ('planning', '0004_v4_creneau_date'),
        ('referentiel', '0010_v8_specialites'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='specialite',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='creneau',
            index=models.Index(fields=['groupe', 'specialite', 'date'], name='creneau_groupe__76b9ce_idx'),
        ),
    ]
