# Generated by Django 6.1 on 2026-08-28 15:31

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.CharField(default=core.utils.generate_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('auteur', models.CharField(max_length=255)),
                ('utilisateur_id', models.CharField(blank=True, max_length=64, null=True)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=512)),
                ('motif', models.TextField()),
                ('creneau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='planning.creneau')),
            ],
            options={
                'db_table': 'audit_entry',
                'indexes': [models.Index(fields=['date_heure'], name='audit_entry_date_he_caf56f_idx')],
            },
        ),
    ]
