# Generated by Django 6.1 on 2026-08-28 15:31

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeEnseignant',
            fields=[
                ('id', models.CharField(default=core.utils.generate_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('absence', 'Absence'), ('report', 'Report'), ('permutation', 'Permutation')], max_length=16)),
                ('statut', models.CharField(choices=[('en_attente', 'En Attente'), ('validee', 'Validee'), ('refusee', 'Refusee')], default='en_attente', max_length=16)),
                ('motif', models.TextField()),
                ('jour_propose', models.CharField(blank=True, choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi')], max_length=16, null=True)),
                ('heure_debut_proposee_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('heure_fin_proposee_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('salle_proposee_id', models.CharField(blank=True, max_length=64, null=True)),
                ('motif_decision', models.TextField(blank=True, null=True)),
                ('decide_par_id', models.CharField(blank=True, max_length=64, null=True)),
                ('decide_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creneau_concerne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_concerne', to='planning.creneau')),
                ('creneau_propose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_propose', to='planning.creneau')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='accounts.enseignant')),
            ],
            options={
                'db_table': 'demande_enseignant',
                'indexes': [models.Index(fields=['enseignant'], name='demande_ens_enseign_423744_idx'), models.Index(fields=['statut'], name='demande_ens_statut_37b9fc_idx')],
            },
        ),
    ]
