# Generated by Django 6.1 on 2026-08-28 15:31

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationItem',
            fields=[
                ('id', models.CharField(default=core.utils.generate_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('modifie', 'Modifie'), ('annule', 'Annule'), ('info', 'Info')], max_length=16)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('lue', models.BooleanField(default=False)),
                ('critique', models.BooleanField(default=False)),
                ('creneau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='planning.creneau')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='accounts.utilisateur')),
            ],
            options={
                'db_table': 'notification_item',
                'indexes': [models.Index(fields=['utilisateur', 'lue'], name='notificatio_utilisa_5f6dba_idx')],
            },
        ),
    ]
